version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8889:8889"  # Prometheus metrics
      - "8888:8888"  # Collector internal metrics

#  jaeger:
#    image: jaegertracing/jaeger:2.4.0
#    container_name: jaeger
#    environment:
#      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
#    ports:
#      - "16686:16686"  # Jaeger UI
#      - "14250:14250"  # gRPC endpoint
#      - "9411:9411"    # Zipkin
#      - "5778:5778"    # Sampling Configuration

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: ["--web.enable-remote-write-receiver", "--config.file=/etc/prometheus/prometheus.yml"]  # ✅ Bổ sung config file
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # ✅ Mount file vào container
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - ./tempo.yml:/etc/tempo.yml  # ✅ Mount file config vào container
    command: ["--config.file=/etc/tempo.yml"]  # ✅ Trỏ đến file config

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana  # Lưu trữ dữ liệu
      - ./grafana-provisioning:/etc/grafana/provisioning  # Auto cấu hình Data Source
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
